### ISSUE TITLE
希望取消单次学习时长，或者能让用户自己设置学习时长。

### ISSUE THREAD

**Issue by HERMITlian** [F4V3Y9D7/Gw2AutoPvp#12]
单次学习时长太短，打两局就没了，希望能取消单次学习时长，或者让用户自己设置。感谢大佬。

**Comment by F4V3Y9D7** [comment]
框架问题，不能一次性超过识图次数上限，否则会崩溃。免费版本不会为框架付费

**Comment by F4V3Y9D7** [comment]
同时也是防止工作室大批量挂机

**Comment by Pine-sha** [comment]
新版本测试中，貌似有一些寻路准确度的bug，会卡在某个角落不动了 = =~
