### ISSUE TITLE
开启之后会一直点队伍，反复卡住

### ISSUE THREAD

**Issue by YanHanYe** [F4V3Y9D7/Gw2AutoPvp#3]
![image](https://github.com/F4V3Y9D7/Gw2AutoPvp/assets/165124984/e9f21aa0-74f9-4319-bb5d-c98aab6f46c7)
d大概是这个位置

**Comment by sunE5** [comment]
我是直接吧pvp改成P按键解决的

**Comment by F4V3Y9D7** [comment]
楼上正解，需要把pvp面板快捷键修改成P，已同步更新使用说明
