### ISSUE TITLE
dx.d3d11 找图可以成功，但是会导致激战2程序崩溃

### ISSUE THREAD

**Issue by clearhill** [F4V3Y9D7/Gw2AutoPvp#4]
我在用Python11 调用op0.4.2的库，可以找图成功，但是程序会奔溃，想请教下，这个程序是否遇到过同样的问题，该如何解决啊，谢谢！

**Comment by F4V3Y9D7** [comment]
游戏必须窗口化，其他原因不明

**Comment by clearhill** [comment]
用了最新的0.4.5，还是同样的问题，我准备继续研究下，有进展会同步！
