### ISSUE TITLE
大佬，最近游戏更新后开启脚本提示 Traceback (most recent call last) : File" D: \Program Files \Gw2AutoPvp\Gw2AutoPvp. py，line 328，in <module> File" D: \Program Files \Gw2AutoPvp \Gw2AutoPvp. py"， line 324, in script_ main File" D: \Program Files \Gw2AutoPvp \Gw2AutoPvp. py，line 302， in begin. pvp  File" D: \Program Files \Gw2AutoPvp \Gw2AutoPvp. py'，line 178， in middle_ game TypeError: cannot unpack non- iterable NoneType object

### ISSUE THREAD

**Issue by jahore** [F4V3Y9D7/Gw2AutoPvp#6]
Traceback (most recent call last) :
 File" D: \Program Files \Gw2AutoPvp\Gw2AutoPvp. py，line 328，in <module>
File" D: \Program Files \Gw2AutoPvp \Gw2AutoPvp. py"， line 324, in script_ main 
File" D: \Program Files \Gw2AutoPvp \Gw2AutoPvp. py，line 302， in begin. pvp 
 File" D: \Program Files \Gw2AutoPvp \Gw2AutoPvp. py'，line 178， in middle_ game
 TypeError: cannot unpack non- iterable NoneType object

请教一下这是软件需要更新吗？
![QQ图片20240422004959](https://github.com/F4V3Y9D7/Gw2AutoPvp/assets/167702362/667793e0-2085-44e8-86bc-0eb059b4ff36)

**Comment by F4V3Y9D7** [comment]
游戏更新了，等脚本更新

**Comment by jahore** [comment]
> 游戏更新了，等脚本更新

谢谢大佬

**Comment by F4V3Y9D7** [comment]
20240423已更新，下载最新发布版

**Comment by jahore** [comment]
> 20240423已更新，下载最新发布版

谢谢大佬，已可用
